//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.28 at 09:51:24 AM UYT 
//


package dian.gov.co.facturaelectronica.structures_2_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Informacion del Proveedor Autorizado (PA) por la DIAN
 * 			
 * 
 * <p>Java class for AuthorizationProvider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthorizationProvider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuthorizationProviderID" type="{dian:gov:co:facturaelectronica:Structures-2-1}coID2Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthorizationProvider", propOrder = {
    "authorizationProviderID"
})
public class AuthorizationProvider {

    @XmlElement(name = "AuthorizationProviderID", required = true)
    protected CoID2Type authorizationProviderID;

    /**
     * Gets the value of the authorizationProviderID property.
     * 
     * @return
     *     possible object is
     *     {@link CoID2Type }
     *     
     */
    public CoID2Type getAuthorizationProviderID() {
        return authorizationProviderID;
    }

    /**
     * Sets the value of the authorizationProviderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoID2Type }
     *     
     */
    public void setAuthorizationProviderID(CoID2Type value) {
        this.authorizationProviderID = value;
    }

}
