//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.28 at 09:51:24 AM UYT 
//


package dian.gov.co.facturaelectronica.structures_2_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.CountryType;
import oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.MonetaryTotalType;
import oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2.IdentifierType;


/**
 * <p>Java class for DianExtensionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DianExtensionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceControl" type="{dian:gov:co:facturaelectronica:Structures-2-1}InvoiceControl" minOccurs="0"/>
 *         &lt;element name="InvoiceSource" type="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}CountryType"/>
 *         &lt;element name="SoftwareProvider" type="{dian:gov:co:facturaelectronica:Structures-2-1}SoftwareProvider"/>
 *         &lt;element name="SoftwareSecurityCode" type="{urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2}IdentifierType"/>
 *         &lt;element name="AuthorizationProvider" type="{dian:gov:co:facturaelectronica:Structures-2-1}AuthorizationProvider"/>
 *         &lt;element name="QRCode" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="AdditionalMonetaryTotal" type="{dian:gov:co:facturaelectronica:Structures-2-1}AdditionalMonetaryTotal" maxOccurs="0" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}LegalMonetaryTotal" minOccurs="0"/>
 *         &lt;element name="FinancialInformation" type="{dian:gov:co:facturaelectronica:Structures-2-1}FinancialInformation" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DianExtensionsType", propOrder = {
    "invoiceControl",
    "invoiceSource",
    "softwareProvider",
    "softwareSecurityCode",
    "authorizationProvider",
    "qrCode",
    "legalMonetaryTotal"
})
public class DianExtensionsType {

    @XmlElement(name = "InvoiceControl")
    protected InvoiceControl invoiceControl;
    @XmlElement(name = "InvoiceSource", required = true)
    protected CountryType invoiceSource;
    @XmlElement(name = "SoftwareProvider", required = true)
    protected SoftwareProvider softwareProvider;
    @XmlElement(name = "SoftwareSecurityCode", required = true)
    protected IdentifierType softwareSecurityCode;
    @XmlElement(name = "AuthorizationProvider", required = true)
    protected AuthorizationProvider authorizationProvider;
    @XmlElement(name = "QRCode", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String qrCode;
    @XmlElement(name = "LegalMonetaryTotal", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")
    protected MonetaryTotalType legalMonetaryTotal;

    /**
     * Gets the value of the invoiceControl property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceControl }
     *     
     */
    public InvoiceControl getInvoiceControl() {
        return invoiceControl;
    }

    /**
     * Sets the value of the invoiceControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceControl }
     *     
     */
    public void setInvoiceControl(InvoiceControl value) {
        this.invoiceControl = value;
    }

    /**
     * Gets the value of the invoiceSource property.
     * 
     * @return
     *     possible object is
     *     {@link CountryType }
     *     
     */
    public CountryType getInvoiceSource() {
        return invoiceSource;
    }

    /**
     * Sets the value of the invoiceSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryType }
     *     
     */
    public void setInvoiceSource(CountryType value) {
        this.invoiceSource = value;
    }

    /**
     * Gets the value of the softwareProvider property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareProvider }
     *     
     */
    public SoftwareProvider getSoftwareProvider() {
        return softwareProvider;
    }

    /**
     * Sets the value of the softwareProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareProvider }
     *     
     */
    public void setSoftwareProvider(SoftwareProvider value) {
        this.softwareProvider = value;
    }

    /**
     * Gets the value of the softwareSecurityCode property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getSoftwareSecurityCode() {
        return softwareSecurityCode;
    }

    /**
     * Sets the value of the softwareSecurityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setSoftwareSecurityCode(IdentifierType value) {
        this.softwareSecurityCode = value;
    }

    /**
     * Gets the value of the authorizationProvider property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationProvider }
     *     
     */
    public AuthorizationProvider getAuthorizationProvider() {
        return authorizationProvider;
    }

    /**
     * Sets the value of the authorizationProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationProvider }
     *     
     */
    public void setAuthorizationProvider(AuthorizationProvider value) {
        this.authorizationProvider = value;
    }

    /**
     * Gets the value of the qrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRCode() {
        return qrCode;
    }

    /**
     * Sets the value of the qrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRCode(String value) {
        this.qrCode = value;
    }

    /**
     * Gets the value of the legalMonetaryTotal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryTotalType }
     *     
     */
    public MonetaryTotalType getLegalMonetaryTotal() {
        return legalMonetaryTotal;
    }

    /**
     * Sets the value of the legalMonetaryTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryTotalType }
     *     
     */
    public void setLegalMonetaryTotal(MonetaryTotalType value) {
        this.legalMonetaryTotal = value;
    }

}
