//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.28 at 09:51:24 AM UYT 
//


package dian.gov.co.facturaelectronica.structures_2_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2.IdentifierType;


/**
 * <p>Java class for SoftwareProvider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoftwareProvider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProviderID" type="{dian:gov:co:facturaelectronica:Structures-2-1}coID2Type"/>
 *         &lt;element name="SoftwareID" type="{urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2}IdentifierType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareProvider", propOrder = {
    "providerID",
    "softwareID"
})
public class SoftwareProvider {

    @XmlElement(name = "ProviderID", required = true)
    protected CoID2Type providerID;
    @XmlElement(name = "SoftwareID", required = true)
    protected IdentifierType softwareID;

    /**
     * Gets the value of the providerID property.
     * 
     * @return
     *     possible object is
     *     {@link CoID2Type }
     *     
     */
    public CoID2Type getProviderID() {
        return providerID;
    }

    /**
     * Sets the value of the providerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoID2Type }
     *     
     */
    public void setProviderID(CoID2Type value) {
        this.providerID = value;
    }

    /**
     * Gets the value of the softwareID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getSoftwareID() {
        return softwareID;
    }

    /**
     * Sets the value of the softwareID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setSoftwareID(IdentifierType value) {
        this.softwareID = value;
    }

}
